
package eu.loxon.centralcontrol;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CentralControl", targetNamespace = "http://www.loxon.eu/CentralControl/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CentralControl {


    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.RadarResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/radar")
    @WebResult(name = "radarResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/radar", output = "http://www.loxon.eu/CentralControl/CentralControl/radarResponse")
    public RadarResponse radar(
        @WebParam(name = "radarRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        RadarRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.ActionCostResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/explodeCell")
    @WebResult(name = "actionCostResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/explodeCell", output = "http://www.loxon.eu/CentralControl/CentralControl/getActionCostResponse")
    public ActionCostResponse getActionCost(
        @WebParam(name = "actionCostRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        ActionCostRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.ExplodeCellResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/explodeCell")
    @WebResult(name = "explodeCellResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/explodeCell", output = "http://www.loxon.eu/CentralControl/CentralControl/explodeCellResponse")
    public ExplodeCellResponse explodeCell(
        @WebParam(name = "explodeCellRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        ExplodeCellRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.GetSpaceShuttlePosResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/getSpaceShuttlePos")
    @WebResult(name = "getSpaceShuttlePosResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/getSpaceShuttlePos", output = "http://www.loxon.eu/CentralControl/CentralControl/getSpaceShuttlePosResponse")
    public GetSpaceShuttlePosResponse getSpaceShuttlePos(
        @WebParam(name = "getSpaceShuttlePosRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        GetSpaceShuttlePosRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.GetSpaceShuttleExitPosResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/getSpaceShuttleExitPos")
    @WebResult(name = "getSpaceShuttleExitPosResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/getSpaceShuttleExitPos", output = "http://www.loxon.eu/CentralControl/CentralControl/getSpaceShuttleExitPosResponse")
    public GetSpaceShuttleExitPosResponse getSpaceShuttleExitPos(
        @WebParam(name = "getSpaceShuttleExitPosRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        GetSpaceShuttleExitPosRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.StructureTunnelResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/structureTunnel")
    @WebResult(name = "structureTunnelResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/structureTunnel", output = "http://www.loxon.eu/CentralControl/CentralControl/structureTunnelResponse")
    public StructureTunnelResponse structureTunnel(
        @WebParam(name = "structureTunnelRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        StructureTunnelRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.WatchResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/watch")
    @WebResult(name = "watchResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/watch", output = "http://www.loxon.eu/CentralControl/CentralControl/watchResponse")
    public WatchResponse watch(
        @WebParam(name = "watchRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        WatchRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.IsMyTurnResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/isMyTurn")
    @WebResult(name = "isMyTurnResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/isMyTurn", output = "http://www.loxon.eu/CentralControl/CentralControl/isMyTurnResponse")
    public IsMyTurnResponse isMyTurn(
        @WebParam(name = "isMyTurnRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        IsMyTurnRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.MoveBuilderUnitResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/moveBuilderUnit")
    @WebResult(name = "moveBuilderUnitResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/moveBuilderUnit", output = "http://www.loxon.eu/CentralControl/CentralControl/moveBuilderUnitResponse")
    public MoveBuilderUnitResponse moveBuilderUnit(
        @WebParam(name = "moveBuilderUnitRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        MoveBuilderUnitRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns eu.loxon.centralcontrol.StartGameResponse
     */
    @WebMethod(action = "http://www.loxon.eu/CentralControl/startGame")
    @WebResult(name = "startGameResponse", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
    @Action(input = "http://www.loxon.eu/CentralControl/startGame", output = "http://www.loxon.eu/CentralControl/CentralControl/startGameResponse")
    public StartGameResponse startGame(
        @WebParam(name = "startGameRequest", targetNamespace = "http://www.loxon.eu/CentralControl/", partName = "parameters")
        StartGameRequest parameters);

}
