
package eu.loxon.centralcontrol;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CentralControlServiceService", targetNamespace = "http://www.loxon.eu/CentralControl/", wsdlLocation = "http://javachallenge.loxon.hu:8443/engine/CentralControl?wsdl")
public class CentralControlServiceService
    extends Service
{

    private final static URL CENTRALCONTROLSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CENTRALCONTROLSERVICESERVICE_EXCEPTION;
    private final static QName CENTRALCONTROLSERVICESERVICE_QNAME = new QName("http://www.loxon.eu/CentralControl/", "CentralControlServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://javachallenge.loxon.hu:8443/engine/CentralControl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTRALCONTROLSERVICESERVICE_WSDL_LOCATION = url;
        CENTRALCONTROLSERVICESERVICE_EXCEPTION = e;
    }

    public CentralControlServiceService() {
        super(__getWsdlLocation(), CENTRALCONTROLSERVICESERVICE_QNAME);
    }

    public CentralControlServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTRALCONTROLSERVICESERVICE_QNAME, features);
    }

    public CentralControlServiceService(URL wsdlLocation) {
        super(wsdlLocation, CENTRALCONTROLSERVICESERVICE_QNAME);
    }

    public CentralControlServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTRALCONTROLSERVICESERVICE_QNAME, features);
    }

    public CentralControlServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentralControlServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CentralControl
     */
    @WebEndpoint(name = "CentralControlPort")
    public CentralControl getCentralControlPort() {
        return super.getPort(new QName("http://www.loxon.eu/CentralControl/", "CentralControlPort"), CentralControl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CentralControl
     */
    @WebEndpoint(name = "CentralControlPort")
    public CentralControl getCentralControlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.loxon.eu/CentralControl/", "CentralControlPort"), CentralControl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTRALCONTROLSERVICESERVICE_EXCEPTION!= null) {
            throw CENTRALCONTROLSERVICESERVICE_EXCEPTION;
        }
        return CENTRALCONTROLSERVICESERVICE_WSDL_LOCATION;
    }

}
